# Generated by Django 3.2.10 on 2023-04-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_logindb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment_des', models.CharField(max_length=1000)),
                ('images', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
